services:
  db:
    image: postgres:18
    container_name: pgdb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5433'
    volumes:
      - pgdata:/var/lib/postgresql
    command: -p 5433
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -p 5433']
      interval: 5s
      retries: 5
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - '8000:8000'
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=pgdb
      - DB_PORT=5433
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    environment:
      # If needed by frontend, setup frontend variables here
      - NODE_ENV=development
      - CI=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
